### ISSUE TITLE
E-signature not prompting for AAD credentials

### ISSUE THREAD

**Issue by c85** [microsoft/azure-redcap-paas#15]
Hello,

E-signatures (an extension of the record locking/unlocking functionality) when toggled will prompt the user for their credentials, however, the credentials prompted for are not AAD credentials (we have Azure OAuth2 authentication method enabled).

![2021-12-07_9-55-08](https://user-images.githubusercontent.com/11774666/145052314-777c64ea-3de1-4c30-93bb-5fa8442639f0.png)

**Comment by SvenAelterman** [comment]
@c85 Thanks for the feedback. This appears to be a REDCap issue and not related to the deployment templates in this repo. As such, I am closing this issue. If I misinterpreted, please put a comment here and I'll re-open it.
