### ISSUE TITLE
Sendmail in Deploy with your SMTP Relay option does not support TLS 1.1 and above

### ISSUE THREAD

**Issue by js10ah** [microsoft/azure-redcap-paas#16]
Sendmail in the **Deploy with your SMTP Relay** option does not support TLS 1.1 and above. This causes the mail function to fail when using an SMTP relay that requires TLS 1.1 or 1.2. The included fake sendmail is no longer actively managed. To fix the issue I used a fork that adds support for TLS 1.1 and 1.2. The original fake sendmail dev also links to the same fork:

https://github.com/sendmail-tls1-2/main

**Comment by SvenAelterman** [comment]
See the comment in #44. We are focusing on Azure Communication Services instead.
