### ISSUE TITLE
Problems with email

### ISSUE THREAD

**Issue by mgabetta** [microsoft/azure-redcap-paas#2]
Hi!
We have deployed RedCAP on Azure resources with the ARM Template. Everything seems to work except the emails. REDCap, in the configuration check page, says that it is able to send emails but no email are sent.
The SMTP configurations are correct (tested with a mail client). Any idea on how we could investigate on the cause of the problem?

**Comment by taylorr4** [comment]
@mgabetta the best place for help with this is to post a question on the REDCap Community site: https://community.projectredcap.org . I'm sure you or a colleague have access there. I personally don't know much about the email system that is the default for this package. (Perhaps you have to set a "Universal From Email Address" on the General Configuration page in the REDCap Control Center.) You might consider asking @bretthackermsft (the creator of this stack) for advise on why it is not sending out email.

**Comment by bretthackermsft** [comment]
The setup routine (https://github.com/Microsoft/azure-redcap-paas/blob/master/deploy.ps1#L168) updates the sendmail.ini file at that line. You can use the Web App Kudu console (https://github.com/projectkudu/kudu/wiki/Accessing-the-kudu-service) to look in that folder and troubleshoot what's going on and review the logs.

**Comment by SvenAelterman** [comment]
I believe this issue was addressed with a recent PR. We discovered a typo in the script.
