### ISSUE TITLE
REDCap requirements for PEAR

### ISSUE THREAD

**Issue by odin88** [Microsoft/azure-redcap-paas#3]
Since this is for App Service (old name is Azure Website), do we still need to configure for PEAR package ? if yes, how we can enable it in Kudu ?

**Comment by taylorr4** [comment]
@odin88 no, you don't need to configure anything for PEAR. While REDCap might utilize parts of PEAR for certain functionality, it is all included internally, so you never have to worry about dealing with it in any way.
