### ISSUE TITLE
Your deployment failed

### ISSUE THREAD

**Issue by emmanuelchevallier** [Microsoft/azure-redcap-paas#4]
Hi,

I have an error deploying RedCAP on Azure "Your deployment failed"

Error message is: 

STATUS  Conflict
STATUS MESSAGE  {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "L'opération de ressource s'est achevée avec l'état d'approvisionnement terminal « Failed »."
  }
}
PROVISIONING STATE  Failed
TIMESTAMP  4/26/2019, 5:11:03 PM
DURATION  39 seconds
TYPE  Microsoft.Web/sites/sourcecontrols

Someone have an idea how to fix it?

May I download and join here the deployment details file?

Best regards,
Emmanuel

**Comment by taylorr4** [comment]
Hi @emmanuelchevallier, unfortunately there's no one on here that might be able to provide any expertise on this. The Microsoft employee who originally created much of this code made it available as-is and does not interact with the REDCap group. I recommend instead to post this on the REDCap Community site for help, and hopefully someone there has some experience to help. I myself have deployed with Azure, but i don't know enough about how to help with this here, unfortunately.

**Comment by emmanuelchevallier** [comment]
Hi @taylorr4,
Thanks for your reply! I will try to find help with REDCAP Community or maybe I will switch to a manual install in an Azure virtual machines.
Thanks again !
Emmanuel
