### ISSUE TITLE
Unable to deploy: Microsoft.Web/sites/sourcecontrols conflict

### ISSUE THREAD

**Issue by aditya10** [microsoft/azure-redcap-paas#6]
Hello! I have been trying deploy REDCap (v8.11.8) using the Deploy using SendGrid template and my deployment is failing with this error:

```
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'."
    }
}
```
<img width="943" alt="Screen Shot 2020-08-04 at 1 15 22 PM" src="https://user-images.githubusercontent.com/7976828/89340542-c2adfa00-d654-11ea-9204-28874414be0f.png">

I am new to Azure and would really appreciate some help. Please let me know if you need any additional information regarding my deployment.

**Comment by aditya10** [comment]
I found a relevant post on the REDCap community.

**Comment by tdannecy** [comment]
> I found a relevant post on the REDCap community.

Can you please share a link to this post?
