### ISSUE TITLE
Remove Private Endpoint for REDCap dashboard app service

### ISSUE THREAD

**Issue by jonny-ibdr** [microsoft/azure-redcap-paas#83]
Hi,

We've noticed if we do an nslookup on the public URL created by the Bicep, it goes to a private link resource. This causes issues when trying to access the redcap API from other resources in azure as it thinks it's a private link resource.

After looking into it, it looks like the private endpoint isn't actually being used for anything, and so should be removed to save costs and reduce complexity.

Thanks

**Comment by SvenAelterman** [comment]
Hi @jonny-ibdr,

Thanks for the feedback! I have a PR that will be created soon that will make the private endpoint optional. 

However, for a production deployment of REDCap, we would generally recommend that the app service is fronted by a network security solution, like Azure Application Gateway. In that case, the public endpoint (possibly only the surveys endpoint) will reside on the App Gateway and the App Gateway will be able to establish connectivity to the backend App Service's private endpoint. (Note that deployment of the App Gateway or other service is outside the scope of this project.)
